### ISSUE TITLE
nvim setup - remember PackerSync

### ISSUE THREAD

**Issue by shawndwells** [3rfaan/arch-everforest#1]
Hey There - following your writeup and using issues to help make a few notes. Hope you don't mind!

When setting up nvim, assuming a new install, it's important to run ``PackerSync``. This can be a 1-liner on the CLI:

```bash
  nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

**Comment by shawndwells** [comment]
Correction.

``
  nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerInstall' &&
  nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
``

**Comment by 3rfaan** [comment]
Thx, I've added this to README.
