### ISSUE TITLE
Incorrect syntax when enabling NVIDIA settings

### ISSUE THREAD

**Issue by Delta0001** [3rfaan/arch-everforest#3]
https://github.com/3rfaan/arch-everforest/blob/a81dc984d572e6487cdcfa60b8b412689c7b1e20/hypr/hyprland.conf#L37

Currently running 33.1

Cursor will simply not appear unless a comma is used as shown in the [example](https://wiki.hyprland.org/Nvidia/#how-to-get-hyprland-to-possibly-work-on-nvidia):

```
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

```

**Comment by 3rfaan** [comment]
Fixed for all environment variables in hyprland.conf.

Thank you!
